extern void reactionGuard(const char* action);
extern void reactionVein(const char* action);
extern void reactionForest(const char* action);
extern void reactionOven(const char* action);
extern void reactionChest(const char* action);
extern void reactionBox(const char* action);
extern void reactionHole(const char* action);
extern void reactionNote(const char* action);
extern void reactionNote(const char* action);